version: '3'

services:
  backend:
    build: ./monsec-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client
    ports:
      - "5001:5000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
